environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 7.9.0 x64
  - npm install -g npm@4 --silent
  - npm install -g gulp mocha --silent

build_script:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test