name: Build + Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]

    name: Build Material Icon Theme

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Setup Platform 🛠
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
        with:
          bun-version: 1.1.13

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - name: Test + Build 🚀
        run: |
          bun test
          bun run vscode:prepublish
