name: Build + Test

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest]

    name: Build Material Icon Theme

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup Platform 🛠
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run display server 🖥
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
        if: ${{ success() }}

      - name: Install dependencies 📦
        run: bun install --frozen-lockfile

      - name: Cache dependencies 💾
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Test + Build 🚀
        run: |
          bun test
          bun run vscode:prepublish
        env:
          DISPLAY: ":99.0"
