name: Icon Review

on:
  pull_request:
    paths:
      - 'icons/*.svg'

jobs:
  icon-review:
    name: Icon Review
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Review SVG files 🔍
        run: |
          svgFiles=$(git diff origin/${{ env.TARGET_BRANCH }} --diff-filter=ACMRTUX  --name-only | grep '.svg$')
          echo "SVG files changed: ${svgFiles}"
          npx svg-icon-review ${svgFiles}

      - name: Upload PNG to Repository ⬆️
        run: |
          mkdir -p review-images
          mv ./preview.png review-images/${{ github.event.pull_request.number }}_${{ github.sha }}.png
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b review-images
          git add review-images/
          git commit -m "Add generated review image"
          git config pull.rebase true
          git push origin review-images

      - name: Post review in PR ✍️
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const pngFilePath = './preview.png';
            const commentBody = '## Preview \n\nPlease check if your contributed icons are looking good both on dark and light theme: \n\n ![Generated PNG](https://raw.githubusercontent.com/' + context.repo.owner + '/' + context.repo.repo + '/' + 'review-images/review-images/${{ github.event.pull_request.number }}_${{ github.sha }}.png) \n\n You can find more information how to contribute in the [contribution guidelines](https://github.com/PKief/vscode-material-icon-theme/blob/main/CONTRIBUTING.md).';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
